services:
  portainer-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portainer-mcp
    ports:
      - "${PORTAINER_MCP_PORT:-9153}:${PORTAINER_MCP_PORT:-9153}"
    env_file:
      - .env
    volumes:
      - portainer-logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6971/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - portainer-mcp-network

volumes:
  portainer-logs:

networks:
  portainer-mcp-network:
    driver: bridge 